foreach(required BUILD_DIR STAGE_DIR WINDEPLOYQT SOURCE_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${STAGE_DIR}")
file(MAKE_DIRECTORY "${STAGE_DIR}")
set(install_command "${CMAKE_COMMAND}" --install "${BUILD_DIR}"
    --prefix "${STAGE_DIR}" --component Application)
if(DEFINED CONFIG AND NOT CONFIG STREQUAL "")
    list(APPEND install_command --config "${CONFIG}")
endif()
execute_process(COMMAND ${install_command} RESULT_VARIABLE install_result)
if(NOT install_result EQUAL 0)
    message(FATAL_ERROR "Could not stage the ParsiNama Windows application")
endif()
set(staged_catalog "${STAGE_DIR}/bin/data/parsinama-catalog.sqlite")
file(REMOVE "${staged_catalog}")
file(CREATE_LINK "${BUILD_DIR}/parsinama-catalog.sqlite" "${staged_catalog}" COPY_ON_ERROR)
execute_process(COMMAND "${WINDEPLOYQT}"
    --qmldir "${SOURCE_DIR}/qml" --compiler-runtime --no-translations
    "${STAGE_DIR}/bin/leomoon-parsinama.exe"
    RESULT_VARIABLE deploy_result)
if(NOT deploy_result EQUAL 0)
    message(FATAL_ERROR "windeployqt failed")
endif()
if(NOT EXISTS "${STAGE_DIR}/bin/sqldrivers/qsqlite.dll")
    message(FATAL_ERROR "The deployed Windows application has no SQLite driver")
endif()
